apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
spec:
  hostAliases:
    - ip: "10.103.59.210"
      hostnames:
      - "stash.bbpd.io"

  containers:
  - name: maven
    image: maven:3.3.9-jdk-8-alpine
    command:
    - cat
    tty: true
  - name: aws-cli
    image: mesosphere/aws-cli
    imagePullPolicy: Always
    command:
    - cat
    tty: true